---
title: "ID5059_1_190018562"
author: "Sophia"
date: "02/03/2022"
output: html_document
---
Please find committed changes in my github repository <https://github.com/selsiekiely/ID5059_190018562>.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import DataSet:

```{r}
vehicles <- read.csv("C:/Users/Sophia/ID5059/vehicles.csv")
head(vehicles)
```

## Testing and Training

We split the data into training and test data using a 80/20 split respectively. Seed is set at last
four digits of student ID number.

```{r}
library(caTools)
set.seed(8562)
split = sample.split(vehicles$price, SplitRatio = 0.8)
training_set = subset(vehicles, split == TRUE)
test_set = subset(vehicles, split == FALSE)
```

We will train on 80% of our data and then test on 20% of the data.

```{r}
colnames(vehicles)
Price <- training_set$price
Region <- as.integer(as.factor(training_set$region))
Year <- training_set$year
par(mfrow=c(3,2))
hist(Price)
boxplot(Price, horizontal=TRUE)
hist(Region)
boxplot(Region, horizontal=TRUE)
hist(Year)
boxplot(Year, horizontal=TRUE)
```

Data Wrangle for purposes of removing "NA"'S and fuller elements

```{r}
```